In [ ]:
# file_aggregator
import csv, os
import shutil
import pandas as pd
import numpy as np
# fileDir = R'C:\Users\akash\Documents\Testing'
# fileOutput = R'C:\Users\akash\Documents\match_scouting_test.csv'
# fileEndDir = R'C:\Users\akash\Documents\endDir'
fileDir = R'C:\Users\Aztechs Robotics\Documents\Match Scouting Data'
fileOutput = R'C:\Users\Aztechs Robotics\Documents\schema.csv'
fileOutput_agg = R'C:\Users\Aztechs Robotics\Documents\match_scouting_2025_agg.csv'
fileOutput_radar = R'C:\Users\Aztechs Robotics\Documents\match_scouting_2025_radar.csv'
fileOutput_comp = R'C:\Users\Aztechs Robotics\Documents\match_scouting_2025_comp.csv'
fileEndDir = R'C:\Users\Aztechs Robotics\Documents\Previously Aggregated Scouting Data'

fileTest = R'C:\Users\Aztechs Robotics\Documents\match_scouting_2025_test.csv'

accepted_comps = {'', 'uvm', 'mayhem', 'battlecry', 'bc', 'minuteman'}
uvm = {69, 95, 157, 166, 237, 348, 811, 839, 1058, 1073, 1512, 1729, 2262, 2370, 2423, 2523, 3323, 
       4311, 4572, 4909, 5494, 5687, 6691, 6933, 7913, 8421, 8544, 9096, 9101, 10066, 10108, 10138, 10647}
mayhem = {131, 157, 166, 190, 319, 501, 1073, 1119, 1153, 1721, 1729, 1735, 1768, 1922, 2342, 2648, 
          3623, 3467, 3597, 5813, 5962, 6324, 8046, 9443}
bc = {48, 78, 88, 126, 131, 138, 151, 157, 166, 175, 177, 190, 238, 319, 467, 501, 694, 1058, 1073, 1100, 1155, 1277,
      1474, 1591, 1729, 1735, 1740, 1757, 1768, 1796, 2053, 2079, 2084, 2262, 2265, 2342, 2370, 2423, 2713, 2791, 
      2876, 2877, 3182, 3467, 4041, 4048, 4311, 4575, 4909, 5422, 5687, 6324, 6328, 7153, 7407, 8085, 8544, 8567, 8708,
      8724, 9443, 9642, 10063, 10229}
minuteman = {157, 175, 190, 663, 1071, 1099, 1119, 1735, 1768, 2064, 3182, 3464, 3467, 3566, 3623, 4169, 4905, 4909, 
             5347, 5422, 5902, 5962, 6328, 6620, 8013, 8708, 9644, 9729, 10063, 10393}



competition = input("Which competition to select? (Leave blank for all)").lower()




with open(fileOutput, 'a') as output:
    for entry in os.listdir(fileDir):
        filePath = fileDir + '\\'+ entry
        with open(filePath, "r") as file:
            data = ""
            data = file.read()
            output.write(data + "\n")
            file.close()
        shutil.move(filePath, fileEndDir)
    output.close()

data = pd.read_csv(fileOutput)

data['Auto'] = data['Auto #Scored Coral L1']*3 + data['Auto #Scored Coral L2']*4 + data['Auto #Scored Coral L3']*6 + data['Auto #Scored Coral L4']*7 + data['Auto #Scored Barge'] *4 + data['Auto #Scored Processor'] * 6 + data['Left Starting Position'] * 3
data['TeleopCoral'] = data['TeleOp #Scored Coral L1']*2 + data['TeleOp #Scored Coral L2']*3 + data['TeleOp #Scored Coral L3']*4 + data['TeleOp #Scored Coral L4']*5
data['TeleopAlgae'] = data['TeleOp #Scored Barge'] * 4 + data['TeleOp #Scored Processor'] * 2
# renaming data
# E.X. [T#SL1] = TeleOp Number Scored Coral L1
# E.X. [T#SP] = TeleOp Number Scored Barge
if(True):
    data['T#SL1'] = data['TeleOp #Scored Coral L1']
    data['T#SL2'] = data['TeleOp #Scored Coral L2']
    data['T#SL3'] = data['TeleOp #Scored Coral L3']
    data['T#SL4'] = data['TeleOp #Scored Coral L4']
    data['T#SB'] = data['TeleOp #Scored Barge']
    data['T#SP'] = data['TeleOp #Scored Processor']
    data['A#SL1'] = data['Auto #Scored Coral L1']
    data['A#SL2'] = data['Auto #Scored Coral L2']
    data['A#SL3'] = data['Auto #Scored Coral L3']
    data['A#SL4'] = data['Auto #Scored Coral L4']
    data['A#SB'] = data['Auto #Scored Barge']
    data['A#SP'] = data['Auto #Scored Processor']
    

    data['T#AL1'] = data['TeleOp #Attempted Coral L1']
    data['T#AL2'] = data['TeleOp #Attempted Coral L2']
    data['T#AL3'] = data['TeleOp #Attempted Coral L3']
    data['T#AL4'] = data['TeleOp #Attempted Coral L4']
    data['T#AB'] = data['TeleOp #Attempted Barge']
    data['T#AP'] = data['TeleOp #Attempted Processor']
    data['A#AL1'] = data['Auto #Attempted Coral L1']
    data['A#AL2'] = data['Auto #Attempted Coral L2']
    data['A#AL3'] = data['Auto #Attempted Coral L3']
    data['A#AL4'] = data['Auto #Attempted Coral L4']
    data['A#AB'] = data['Auto #Attempted Barge']
    data['A#AP'] = data['Auto #Attempted Processor']
    
mapping = {
    "Park": 2,
    "Hang Deep": 12,
    "Hang Shallow": 6
}
data["Endgame"] = data["Park/Shallow/Deep"].map(mapping).fillna(0).astype(int)

if(competition == 'uvm'):
    df_comp = data[data['Team Number'].isin(uvm)]
    print("Only UVM teams")
elif(competition == 'mayhem'):
    df_comp = data[data['Team Number'].isin(mayhem)]
    print("Only Mayhem teams")
elif(competition == 'battlecry' or competition == 'bc'):
    df_comp = data[data['Team Number'].isin(bc)]
    bc_copy = [x for x in bc if x not in data['Team Number'].tolist()]
    bc_copy.sort()
    print(bc_copy)
    print("Only Battlecry Teams")
else:
    df_comp = data
    print("All teams")



# df_comp.drop(inplace=True, columns=[col for col in df_comp.columns if '#Attempted' in col]+[col for col in df_comp.columns if '#Scored' in col])


col_to_drop = "Competition Location"
value_to_drop = "Test"
data_exclude_test = df_comp[~df_comp[col_to_drop].str.contains(value_to_drop, na=False)]
data_exclude_test.to_csv(fileOutput_comp)

# Match sheet data field
ms_df = data_exclude_test.groupby("Team Number")[["Auto", "TeleopCoral", "TeleopAlgae", "Endgame"] + [col for col in data_exclude_test.columns if 'A#' in col] + [col for col in data_exclude_test.columns if 'T#' in col]].mean(numeric_only=True).reset_index()


ms_df['Auto Score'] = ms_df['Auto']
# ms_df['Auto Acc'] = (ms_df['A#SL1']+ms_df['A#SL2']+ms_df['A#SL3']+ms_df['A#SL4']+ms_df["A#SP"]+ms_df['A#SB'])/(ms_df['A#AL1']+ms_df['A#AL2']+ms_df['A#AL3']+ms_df['A#AL4']+ms_df["A#AP"]+ms_df['A#AB'])
ms_df['Auto Coral'] = ms_df['A#SL1']*3+ms_df['A#SL2']*4+ms_df['A#SL3']*6+ms_df['A#SL4']*7
ms_df['Auto Algae'] = ms_df["A#SP"]*2+ms_df['A#SB']*4

ms_df['Teleop Score'] = ms_df['TeleopCoral'] + ms_df['TeleopAlgae']
ms_df['L1'] = ms_df['T#SL1']*2
ms_df['L2'] = ms_df['T#SL2']*3
ms_df['L3'] = ms_df['T#SL3']*4
ms_df['L4'] = ms_df['T#SL4']*5
ms_df['Processor'] = ms_df['T#SP']*2
ms_df['Barge'] = ms_df['T#SB']*4

ms_df['Endgame Score'] = ms_df['Endgame']
ms_df['Total Score'] = ms_df['Auto']+ms_df['TeleopCoral']+ms_df['TeleopAlgae']+ms_df['Endgame']

ms_df['AutoNorm'] = ms_df['Auto'] / ms_df['Auto'].max()
ms_df['L1Norm'] = ms_df['T#SL1'] / ms_df['T#SL1'].max()
ms_df['L2Norm'] = ms_df['T#SL2'] / ms_df['T#SL2'].max()
ms_df['L3Norm'] = ms_df['T#SL3'] / ms_df['T#SL3'].max()
ms_df['L4Norm'] = ms_df['T#SL4'] / ms_df['T#SL4'].max()
ms_df['TeleopAlgaeNorm'] = ms_df['TeleopAlgae'] / ms_df['TeleopAlgae'].max()
ms_df['EndgameNorm'] = ms_df['Endgame'] / ms_df['Endgame'].max()

ms_df['Auto Coral Acc'] = (ms_df['A#SL1']+ms_df['A#SL2']+ms_df['A#SL3']+ms_df['A#SL4'])/(ms_df['A#AL1']+ms_df['A#AL2']+ms_df['A#AL3']+ms_df['A#AL4'])
ms_df['Auto Algae Acc'] = (ms_df["A#SP"]+ms_df['A#SB'])/(ms_df["A#AP"]+ms_df['A#AB'])
ms_df['L1 Acc']=ms_df['T#SL1']/ms_df['T#AL1']
ms_df['L2 Acc']=ms_df['T#SL2']/ms_df['T#AL2']
ms_df['L3 Acc']=ms_df['T#SL3']/ms_df['T#AL3']
ms_df['L4 Acc']=ms_df['T#SL4']/ms_df['T#AL4']
ms_df['Processor Acc'] = ms_df['T#SP']/ms_df['T#AP']
ms_df['Barge Acc'] = ms_df['T#SB']/ms_df['T#AB']

ms_df.drop(columns=["Auto", "TeleopCoral", "TeleopAlgae", "Endgame"] + [col for col in data_exclude_test.columns if 'A#' in col] + [col for col in data_exclude_test.columns if 'T#' in col], inplace=True)
ms_df.replace(np.inf, 0, inplace=True)
ms_df.to_csv(fileOutput_agg)


# Radar Sheet Data Field
radar_norm = data_exclude_test.groupby("Team Number")[["Auto", "TeleopAlgae", "Endgame", "T#SL1", "T#SL2", "T#SL3", 
                                                       "T#SL4"]].mean().reset_index()
radar_norm['AutoNorm'] = radar_norm['Auto'] / radar_norm['Auto'].max()
radar_norm['L1'] = radar_norm['T#SL1'] / radar_norm['T#SL1'].max()
radar_norm['L2'] = radar_norm['T#SL2'] / radar_norm['T#SL2'].max()
radar_norm['L3'] = radar_norm['T#SL3'] / radar_norm['T#SL3'].max()
radar_norm['L4'] = radar_norm['T#SL4'] / radar_norm['T#SL4'].max()
radar_norm['TeleopAlgaeNorm'] = radar_norm['TeleopAlgae'] / radar_norm['TeleopAlgae'].max()
radar_norm['EndgameNorm'] = radar_norm['Endgame'] / radar_norm['Endgame'].max()

radar_norm.drop(columns=["Auto", "TeleopAlgae", "Endgame", "T#SL1", "T#SL2", "T#SL3", "T#SL4"], inplace=True)

radar_norm = radar_norm[['Team Number', 'TeleopAlgaeNorm','L1','L2','L3','L4','AutoNorm','EndgameNorm']]

radar_norm.to_csv(fileOutput_radar)


print ("Teams: " + str(len(radar_norm)))
print("Process Finished")

In [45]:
import csv, os
import shutil
import pandas as pd
import numpy as np

ranier_dir = "/mnt/home/ranier-gran/Documents/Robotics/Scouting2026/"
ranier_dir = ""

# Run only to clear data

In [46]:
schema_path = ranier_dir + "schemas/"
full_df = pd.read_excel(schema_path + "Schema.xlsx")
full_df

Empty DataFrame
Columns: [Competition, randomNum, Scout, TeamNum, TeamColor, MatchNum, PreloadedFuel, StartingPos, AutoScored, AutoAccuracy, AutoPassed, AutoHang, TeleopScored, TeleopAccuracy, TeleopPassed, HangStatus, HangTime, AccuracyPos, OverBump, UnderTrench, PlayedDefense, CollectedFuel, PassedFuel, DidNothing, Other, Defense, StopReason, Rank, CommentsCNC]
Index: []

[0 rows x 29 columns]

In [47]:
match_csv_path = ranier_dir + "matchData/"
processed_csv_path = ranier_dir + "processedData/"

# Run each time you add data to your match data folder

In [163]:
match_data_dir = os.listdir(match_csv_path)
match_data_dir

[]

In [164]:
def process_match_sheet(full_df, match_csv_path, sheet_name):
    match_df = pd.read_csv(match_csv_path + sheet_name, header = None)
    match_df.drop(29, axis=1, inplace=True)
    match_df.columns = full_df.columns
    full_df = pd.concat([full_df, match_df], ignore_index = True)
    return full_df

In [165]:
for file_name in match_data_dir:
    full_df = process_match_sheet(full_df, match_csv_path, file_name)
    shutil.move(match_csv_path + file_name, processed_csv_path + file_name)
full_df

,Competition,randomNum,Scout,TeamNum,TeamColor,MatchNum,PreloadedFuel,StartingPos,AutoScored,AutoAccuracy,...,UnderTrench,PlayedDefense,CollectedFuel,PassedFuel,DidNothing,Other,Defense,StopReason,Rank,CommentsCNC
0,Minuteman,1,Leo,175,7,Blue,True,Position 2,7,75%,...,False,True,True,False,False,False,Light Defense,Not stopped,Rank 2,NaN
1,Minuteman,1,Leo,3467,3,Blue,True,Position 1,15,75%,...,True,False,True,True,False,False,No Defense,Physically Broke,Rank 1,NaN
2,Minuteman,1,Leo,9725,4,Blue,True,Position 3,5,Less Than 10%,...,True,False,True,False,False,False,Heavy Defense,Not stopped,Rank 3,NaN
3,Minuteman,1,Julia,10063,7,Red,True,Position 2,5,Less Than 10%,...,True,True,False,False,False,False,Light Defense,Not stopped,Rank 3,NaN
4,Minuteman,1,Julia,10393,Red,12,False,Position 1,NaN,Less Than 10%,...,False,False,False,False,False,True,Light Defense,Not stopped,Rank 3,Tried to push the fuel the entire match (think...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,Minuteman,1,Leo,3464,Red,48,True,Position 1,1,Less Than 10%,...,False,True,False,True,False,False,No Defense,Not stopped,Rank 3,NaN
88,Minuteman,1,Leo,3467,Red,49,True,Position 1,40,75%,...,True,False,True,True,False,False,Heavy Defense,Not stopped,Rank 1,NaN
89,Minuteman,1,Julia,3566,Blue,48,True,Position 2,10,More than 95%,...,True,False,False,False,False,True,No Defense,Not stopped,Rank 3,Pushed fuel into the outpost
90,Minuteman,1,Leo,4169,Red,47,True,Position 3,2,Less Than 10%,...,False,False,True,False,False,False,Light Defense,E-stopped,Rank 3,NaN
91,Minuteman,1,Rob,6620,Red,48,False,Position 1,NaN,Less Than 10%,...,False,True,False,True,False,False,No Defense,Not stopped,Rank 2,NaN

In [166]:
full_df_dummies = full_df.copy()
full_df_dummies['AutoAccuracyNum'] = full_df_dummies['AutoAccuracy'].str[-3:-1].astype(float)/100
full_df_dummies['TeleopAccuracyNum'] = full_df_dummies['TeleopAccuracy'].str[-3:-1].astype(float)/100
columns_to_encode = ['AutoHang','HangStatus','AccuracyPos','OverBump','UnderTrench','PlayedDefense','CollectedFuel','PassedFuel','DidNothing','Other','Defense','StopReason']
full_dummies_df = pd.get_dummies(full_df_dummies, columns=columns_to_encode)
print("\nEncoded DataFrame:")
full_dummies_df

Encoded DataFrame:

,Competition,randomNum,Scout,TeamNum,TeamColor,MatchNum,PreloadedFuel,StartingPos,AutoScored,AutoAccuracy,...,DidNothing_True,Other_False,Other_True,Defense_Heavy Defense,Defense_Light Defense,Defense_No Defense,StopReason_Died,StopReason_E-stopped,StopReason_Not stopped,StopReason_Physically Broke
0,Minuteman,1,Leo,175,7,Blue,True,Position 2,7,75%,...,False,True,False,False,True,False,False,False,True,False
1,Minuteman,1,Leo,3467,3,Blue,True,Position 1,15,75%,...,False,True,False,False,False,True,False,False,False,True
2,Minuteman,1,Leo,9725,4,Blue,True,Position 3,5,Less Than 10%,...,False,True,False,True,False,False,False,False,True,False
3,Minuteman,1,Julia,10063,7,Red,True,Position 2,5,Less Than 10%,...,False,True,False,False,True,False,False,False,True,False
4,Minuteman,1,Julia,10393,Red,12,False,Position 1,NaN,Less Than 10%,...,False,False,True,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,Minuteman,1,Leo,3464,Red,48,True,Position 1,1,Less Than 10%,...,False,True,False,False,False,True,False,False,True,False
88,Minuteman,1,Leo,3467,Red,49,True,Position 1,40,75%,...,False,True,False,True,False,False,False,False,True,False
89,Minuteman,1,Julia,3566,Blue,48,True,Position 2,10,More than 95%,...,False,False,True,False,False,True,False,False,True,False
90,Minuteman,1,Leo,4169,Red,47,True,Position 3,2,Less Than 10%,...,False,True,False,False,True,False,False,True,False,False
91,Minuteman,1,Rob,6620,Red,48,False,Position 1,NaN,Less Than 10%,...,False,True,False,False,False,True,False,False,True,False

In [167]:
full_dummies_df.to_csv("data_hub/match_data_hub.csv", index=False)

In [168]:
match_data_dir = os.listdir(match_csv_path)
match_data_dir

[]

In [169]:
competition_dict = {
    "UVM": {
        "Week": 4, 
        "Teams": [157, 190, 1100, 175, 75, 88, 6328],
    },
    "WPI": {
        "Week": 5,
        "Teams": [97, 157, 190, 237, 348, 467, 716, 999, 1027, 
                 1100, 1474, 1740, 1757, 1768, 2079, 2168, 2262,
                 2370, 3205, 3467, 3634, 4048, 4628, 5000, 5112,
                 5347, 5422, 5491, 5494, 6333, 6762, 7760, 8544, 
                 8567, 8724, 9644, 10254, 10393, 11483],
    },
    "Battlecry": {
        "Week": 12,
        "Teams": [157, 190, 1100, 64383, 8888]
    },
    "Minuteman": {
        "Week": 1,
        "Teams": [157, 175, 663, 1071, 1099, 1119, 1735, 1768,
                 2064, 3182, 3464, 3467, 3566, 3623, 4169, 4905,
                 4909, 5347, 5422, 5902, 5962, 6328, 6620, 8013, 
                 8708, 9644, 9729, 10063, 10393]
    },
}
competition_dict

{'UVM': {'Week': 5, 'Teams': [157, 190, 1100, 175, 75, 88, 6328]},
 'WPI': {'Week': 4, 'Teams': [157, 190, 1100, 10053, 12566]},
 'Battlecry': {'Week': 12, 'Teams': [157, 190, 1100, 64383, 8888]},
 'Minuteman': {'Week': 1,
  'Teams': [157,
   175,
   663,
   1071,
   1099,
   1119,
   1735,
   1768,
   2064,
   3182,
   3464,
   3467,
   3566,
   3623,
   4169,
   4905,
   4909,
   5347,
   5422,
   5902,
   5962,
   6328,
   6620,
   8013,
   8708,
   9644,
   9729,
   10063,
   10393]}}

In [170]:
competition_name = 'Minuteman'
competition_df = full_dummies_df[full_dummies_df['TeamNum'].isin(competition_dict[competition_name]['Teams'])]
competition_df

,Competition,randomNum,Scout,TeamNum,TeamColor,MatchNum,PreloadedFuel,StartingPos,AutoScored,AutoAccuracy,...,DidNothing_True,Other_False,Other_True,Defense_Heavy Defense,Defense_Light Defense,Defense_No Defense,StopReason_Died,StopReason_E-stopped,StopReason_Not stopped,StopReason_Physically Broke
0,Minuteman,1,Leo,175,7,Blue,True,Position 2,7,75%,...,False,True,False,False,True,False,False,False,True,False
1,Minuteman,1,Leo,3467,3,Blue,True,Position 1,15,75%,...,False,True,False,False,False,True,False,False,False,True
3,Minuteman,1,Julia,10063,7,Red,True,Position 2,5,Less Than 10%,...,False,True,False,False,True,False,False,False,True,False
4,Minuteman,1,Julia,10393,Red,12,False,Position 1,NaN,Less Than 10%,...,False,False,True,False,True,False,False,False,True,False
5,Minuteman,1,Becky,10393,8,Red,False,Position 2,NaN,More than 95%,...,False,True,False,False,False,True,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,Minuteman,1,Leo,3464,Red,48,True,Position 1,1,Less Than 10%,...,False,True,False,False,False,True,False,False,True,False
88,Minuteman,1,Leo,3467,Red,49,True,Position 1,40,75%,...,False,True,False,True,False,False,False,False,True,False
89,Minuteman,1,Julia,3566,Blue,48,True,Position 2,10,More than 95%,...,False,False,True,False,False,True,False,False,True,False
90,Minuteman,1,Leo,4169,Red,47,True,Position 3,2,Less Than 10%,...,False,True,False,False,True,False,False,True,False,False
91,Minuteman,1,Rob,6620,Red,48,False,Position 1,NaN,Less Than 10%,...,False,True,False,False,False,True,False,False,True,False

In [171]:
competition_df.columns

Index(['Competition', 'randomNum', 'Scout', 'TeamNum', 'TeamColor', 'MatchNum',
       'PreloadedFuel', 'StartingPos', 'AutoScored', 'AutoAccuracy',
       'AutoPassed', 'TeleopScored', 'TeleopAccuracy', 'TeleopPassed',
       'HangTime', 'Rank', 'CommentsCNC', 'AutoAccuracyNum',
       'TeleopAccuracyNum', 'AutoHang_False', 'HangStatus_Level 1',
       'AccuracyPos_About the same', 'AccuracyPos_Consistently bad accuracy',
       'AccuracyPos_When unmoving', 'OverBump_False', 'OverBump_True',
       'UnderTrench_False', 'UnderTrench_True', 'PlayedDefense_False',
       'PlayedDefense_True', 'CollectedFuel_False', 'CollectedFuel_True',
       'PassedFuel_False', 'PassedFuel_True', 'DidNothing_False',
       'DidNothing_True', 'Other_False', 'Other_True', 'Defense_Heavy Defense',
       'Defense_Light Defense', 'Defense_No Defense', 'StopReason_Died',
       'StopReason_E-stopped', 'StopReason_Not stopped',
       'StopReason_Physically Broke'],
      dtype='object')

In [172]:
for col in competition_df.columns:
    if col not in ['TeamNum','MatchNum','randomNum', 'PreloadedFuel', 'CommentsCNC']:
        try:
            competition_df[col] = competition_df[col].astype('float64') # Convert to float64
        except:
            print(f"Could not convert column '{col}' to float64")
if "HangStatus_Level 1" not in competition_df.columns:
    competition_df['HangStatus_Level 1'] = 0
if "HangStatus_Level 2" not in competition_df.columns:
    competition_df['HangStatus_Level 2'] = 0
if "HangStatus_Level 3" not in competition_df.columns:
    competition_df['HangStatus_Level 3'] = 0
if "AutoHang_True" not in competition_df.columns:
    competition_df['AutoHang_True'] = 0

Could not convert column 'Competition' to float64
Could not convert column 'Scout' to float64
Could not convert column 'TeamColor' to float64
Could not convert column 'StartingPos' to float64
Could not convert column 'AutoAccuracy' to float64
Could not convert column 'TeleopAccuracy' to float64
Could not convert column 'Rank' to float64

C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df['HangStatus_Level 2'] = 0
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df['HangStatus_Level 3'] = 0
C:\Users\every\AppData\Local\Temp\ipykernel_41712\300723034.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df['AutoHang_True'] = 0

In [173]:
competition_df.to_csv(f"data_hub/{competition_name}_team_match_data.csv", index = False)

In [174]:
competition_aggregate = competition_df.groupby('TeamNum').mean(numeric_only=True).reset_index()
competition_aggregate['TeleopHangTotal'] = competition_aggregate['HangStatus_Level 1'] * 10 + competition_aggregate['HangStatus_Level 2'] * 20 + competition_aggregate['HangStatus_Level 3'] * 30
competition_aggregate['AutoHangTotal'] = competition_aggregate['AutoHang_True'] * 15
competition_aggregate['HangTotal'] = competition_aggregate['AutoHangTotal'] + competition_aggregate['TeleopHangTotal']
competition_aggregate['PassedTotal'] = competition_aggregate['AutoPassed'] + competition_aggregate['TeleopPassed']
competition_aggregate

,TeamNum,AutoScored,AutoPassed,TeleopScored,TeleopPassed,HangTime,AutoAccuracyNum,TeleopAccuracyNum,AutoHang_False,HangStatus_Level 1,...,StopReason_E-stopped,StopReason_Not stopped,StopReason_Physically Broke,HangStatus_Level 2,HangStatus_Level 3,AutoHang_True,TeleopHangTotal,AutoHangTotal,HangTotal,PassedTotal
0,157,28.666667,NaN,26.000000,22.500000,0.000000,0.737500,0.587500,1.0,0.000000,...,0.0,0.750000,0.250000,0.0,0.0,0.0,0.000000,0.0,0.000000,NaN
1,175,6.750000,NaN,22.750000,2.500000,6.250000,0.637500,0.750000,1.0,1.000000,...,0.0,1.000000,0.000000,0.0,0.0,0.0,10.000000,0.0,10.000000,NaN
2,663,5.000000,NaN,16.000000,0.333333,0.000000,0.800000,0.950000,1.0,0.000000,...,0.0,1.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,NaN
3,1071,NaN,NaN,10.666667,0.000000,0.000000,0.100000,0.450000,1.0,0.000000,...,0.0,1.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,NaN
4,1099,NaN,NaN,0.666667,0.000000,0.000000,0.233333,0.516667,1.0,0.000000,...,0.0,1.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,NaN
5,1119,12.000000,NaN,25.000000,0.000000,0.000000,0.666667,0.750000,1.0,0.000000,...,0.0,1.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,NaN
6,1735,NaN,5.0,2.000000,26.666667,0.000000,0.650000,0.583333,1.0,0.000000,...,0.0,1.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,31.666667
7,1768,40.000000,NaN,173.333333,30.000000,0.000000,0.800000,0.750000,1.0,0.000000,...,0.0,1.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,NaN
8,2064,10.000000,NaN,6.666667,0.000000,0.000000,0.316667,0.425000,1.0,0.000000,...,0.0,0.000000,0.333333,0.0,0.0,0.0,0.000000,0.0,0.000000,NaN
9,3182,NaN,NaN,0.000000,0.000000,0.000000,0.300000,0.300000,1.0,0.000000,...,0.0,1.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,NaN
10,3464,5.500000,NaN,0.000000,0.000000,0.000000,0.300000,0.300000,1.0,0.000000,...,0.0,1.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,NaN
11,3467,41.000000,NaN,122.000000,49.200000,0.000000,0.830000,0.950000,1.0,0.000000,...,0.0,0.600000,0.400000,0.0,0.0,0.0,0.000000,0.0,0.000000,NaN
12,3566,9.000000,NaN,28.333333,0.000000,0.000000,0.950000,0.950000,1.0,0.000000,...,0.0,1.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,NaN
13,3623,6.000000,NaN,14.333333,0.000000,3.333333,0.233333,0.750000,1.0,0.333333,...,0.0,1.000000,0.000000,0.0,0.0,0.0,3.333333,0.0,3.333333,NaN
14,4169,2.000000,NaN,5.500000,2.500000,0.000000,0.300000,0.300000,1.0,0.000000,...,0.5,0.500000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,NaN
15,4905,3.500000,NaN,25.000000,0.000000,0.000000,0.600000,0.816667,1.0,0.000000,...,0.0,1.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,NaN
16,4909,31.666667,NaN,112.333333,43.333333,0.000000,0.883333,0.883333,1.0,0.000000,...,0.0,1.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,NaN
17,5347,NaN,NaN,53.666667,0.000000,0.000000,0.516667,0.666667,1.0,0.000000,...,0.0,0.666667,0.333333,0.0,0.0,0.0,0.000000,0.0,0.000000,NaN
18,5422,15.500000,NaN,87.500000,5.000000,0.000000,0.725000,0.850000,1.0,0.000000,...,0.0,1.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,NaN
19,5902,NaN,NaN,7.500000,20.000000,0.000000,0.412500,0.362500,1.0,0.000000,...,0.0,1.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,NaN
20,5962,11.666667,NaN,21.333333,0.000000,0.000000,0.650000,0.816667,1.0,0.000000,...,0.0,1.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,NaN
21,6328,41.666667,0.0,101.666667,15.000000,0.000000,0.950000,0.950000,1.0,0.000000,...,0.0,1.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,15.000000
22,6620,1.000000,NaN,6.500000,0.000000,0.000000,0.100000,0.612500,1.0,0.000000,...,0.0,1.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,NaN
23,8013,10.333333,NaN,101.250000,33.250000,0.000000,0.687500,0.666667,1.0,0.000000,...,0.0,1.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,NaN
24,8708,0.000000,NaN,13.000000,1.666667,0.000000,0.733333,0.100000,1.0,0.000000,...,0.0,0.666667,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,NaN
25,9644,NaN,NaN,4.333333,11.666667,0.000000,0.366667,0.450000,1.0,0.000000,...,0.0,1.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,NaN
26,9729,5.000000,NaN,23.333333,0.000000,0.000000,0.283333,0.666667,1.0,0.000000,...,0.0,1.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,NaN
27,10063,5.000000,0.0,2.333333,17.333333,0.000000,0.450000,0.366667,1.0,0.000000,...,0.0,1.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,17.333333
28,10393,NaN,NaN,0.000000,0.000000,0.000000,0.383333,0.383333,1.0,0.000000,...,0.0,1.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,NaN

In [175]:
competition_aggregate.columns

Index(['TeamNum', 'AutoScored', 'AutoPassed', 'TeleopScored', 'TeleopPassed',
       'HangTime', 'AutoAccuracyNum', 'TeleopAccuracyNum', 'AutoHang_False',
       'HangStatus_Level 1', 'AccuracyPos_About the same',
       'AccuracyPos_Consistently bad accuracy', 'AccuracyPos_When unmoving',
       'OverBump_False', 'OverBump_True', 'UnderTrench_False',
       'UnderTrench_True', 'PlayedDefense_False', 'PlayedDefense_True',
       'CollectedFuel_False', 'CollectedFuel_True', 'PassedFuel_False',
       'PassedFuel_True', 'DidNothing_False', 'DidNothing_True', 'Other_False',
       'Other_True', 'Defense_Heavy Defense', 'Defense_Light Defense',
       'Defense_No Defense', 'StopReason_Died', 'StopReason_E-stopped',
       'StopReason_Not stopped', 'StopReason_Physically Broke',
       'HangStatus_Level 2', 'HangStatus_Level 3', 'AutoHang_True',
       'TeleopHangTotal', 'AutoHangTotal', 'HangTotal', 'PassedTotal'],
      dtype='object')

In [176]:
competition_aggregate.to_csv(f"data_hub/{competition_name}_team_aggregate_data.csv", index = False)

In [177]:
competition_norm = competition_aggregate[['TeamNum', 'AutoScored','AutoPassed','TeleopScored','TeleopPassed', 'PassedTotal', 'HangTotal']]
competition_norm['AutoScoredNorm'] = competition_norm['AutoScored'] / competition_norm['AutoScored'].max()
competition_norm['AutoPassedNorm'] = competition_norm['AutoPassed'] / competition_norm['AutoPassed'].max()
competition_norm['TeleopScoredNorm'] = competition_norm['TeleopScored'] / competition_norm['TeleopScored'].max()
competition_norm['TeleopPassedNorm'] = competition_norm['TeleopPassed'] / competition_norm['TeleopPassed'].max()
competition_norm['PassedTotalNorm'] = competition_norm['PassedTotal'] / competition_norm['PassedTotal'].max()
competition_norm['HangTotalNorm'] = competition_norm['HangTotal'] / competition_norm['HangTotal'].max()
competition_norm

C:\Users\every\AppData\Local\Temp\ipykernel_41712\2039474675.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_norm['AutoScoredNorm'] = competition_norm['AutoScored'] / competition_norm['AutoScored'].max()
C:\Users\every\AppData\Local\Temp\ipykernel_41712\2039474675.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_norm['AutoPassedNorm'] = competition_norm['AutoPassed'] / competition_norm['AutoPassed'].max()
C:\Users\every\AppData\Local\Temp\ipykernel_41712\2039474675.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_norm['TeleopScoredNorm'] = competition_norm['TeleopScored'] / competition_norm['TeleopScored'].max()
C:\Users\every\AppData\Local\Temp\ipykernel_41712\2039474675.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_norm['TeleopPassedNorm'] = competition_norm['TeleopPassed'] / competition_norm['TeleopPassed'].max()
C:\Users\every\AppData\Local\Temp\ipykernel_41712\2039474675.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_norm['PassedTotalNorm'] = competition_norm['PassedTotal'] / competition_norm['PassedTotal'].max()
C:\Users\every\AppData\Local\Temp\ipykernel_41712\2039474675.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_norm['HangTotalNorm'] = competition_norm['HangTotal'] / competition_norm['HangTotal'].max()

,TeamNum,AutoScored,AutoPassed,TeleopScored,TeleopPassed,PassedTotal,HangTotal,AutoScoredNorm,AutoPassedNorm,TeleopScoredNorm,TeleopPassedNorm,PassedTotalNorm,HangTotalNorm
0,157,28.666667,NaN,26.000000,22.500000,NaN,0.000000,0.688,NaN,0.150000,0.457317,NaN,0.000000
1,175,6.750000,NaN,22.750000,2.500000,NaN,10.000000,0.162,NaN,0.131250,0.050813,NaN,1.000000
2,663,5.000000,NaN,16.000000,0.333333,NaN,0.000000,0.120,NaN,0.092308,0.006775,NaN,0.000000
3,1071,NaN,NaN,10.666667,0.000000,NaN,0.000000,NaN,NaN,0.061538,0.000000,NaN,0.000000
4,1099,NaN,NaN,0.666667,0.000000,NaN,0.000000,NaN,NaN,0.003846,0.000000,NaN,0.000000
5,1119,12.000000,NaN,25.000000,0.000000,NaN,0.000000,0.288,NaN,0.144231,0.000000,NaN,0.000000
6,1735,NaN,5.0,2.000000,26.666667,31.666667,0.000000,NaN,1.0,0.011538,0.542005,1.000000,0.000000
7,1768,40.000000,NaN,173.333333,30.000000,NaN,0.000000,0.960,NaN,1.000000,0.609756,NaN,0.000000
8,2064,10.000000,NaN,6.666667,0.000000,NaN,0.000000,0.240,NaN,0.038462,0.000000,NaN,0.000000
9,3182,NaN,NaN,0.000000,0.000000,NaN,0.000000,NaN,NaN,0.000000,0.000000,NaN,0.000000
10,3464,5.500000,NaN,0.000000,0.000000,NaN,0.000000,0.132,NaN,0.000000,0.000000,NaN,0.000000
11,3467,41.000000,NaN,122.000000,49.200000,NaN,0.000000,0.984,NaN,0.703846,1.000000,NaN,0.000000
12,3566,9.000000,NaN,28.333333,0.000000,NaN,0.000000,0.216,NaN,0.163462,0.000000,NaN,0.000000
13,3623,6.000000,NaN,14.333333,0.000000,NaN,3.333333,0.144,NaN,0.082692,0.000000,NaN,0.333333
14,4169,2.000000,NaN,5.500000,2.500000,NaN,0.000000,0.048,NaN,0.031731,0.050813,NaN,0.000000
15,4905,3.500000,NaN,25.000000,0.000000,NaN,0.000000,0.084,NaN,0.144231,0.000000,NaN,0.000000
16,4909,31.666667,NaN,112.333333,43.333333,NaN,0.000000,0.760,NaN,0.648077,0.880759,NaN,0.000000
17,5347,NaN,NaN,53.666667,0.000000,NaN,0.000000,NaN,NaN,0.309615,0.000000,NaN,0.000000
18,5422,15.500000,NaN,87.500000,5.000000,NaN,0.000000,0.372,NaN,0.504808,0.101626,NaN,0.000000
19,5902,NaN,NaN,7.500000,20.000000,NaN,0.000000,NaN,NaN,0.043269,0.406504,NaN,0.000000
20,5962,11.666667,NaN,21.333333,0.000000,NaN,0.000000,0.280,NaN,0.123077,0.000000,NaN,0.000000
21,6328,41.666667,0.0,101.666667,15.000000,15.000000,0.000000,1.000,0.0,0.586538,0.304878,0.473684,0.000000
22,6620,1.000000,NaN,6.500000,0.000000,NaN,0.000000,0.024,NaN,0.037500,0.000000,NaN,0.000000
23,8013,10.333333,NaN,101.250000,33.250000,NaN,0.000000,0.248,NaN,0.584135,0.675813,NaN,0.000000
24,8708,0.000000,NaN,13.000000,1.666667,NaN,0.000000,0.000,NaN,0.075000,0.033875,NaN,0.000000
25,9644,NaN,NaN,4.333333,11.666667,NaN,0.000000,NaN,NaN,0.025000,0.237127,NaN,0.000000
26,9729,5.000000,NaN,23.333333,0.000000,NaN,0.000000,0.120,NaN,0.134615,0.000000,NaN,0.000000
27,10063,5.000000,0.0,2.333333,17.333333,17.333333,0.000000,0.120,0.0,0.013462,0.352304,0.547368,0.000000
28,10393,NaN,NaN,0.000000,0.000000,NaN,0.000000,NaN,NaN,0.000000,0.000000,NaN,0.000000

In [178]:
competition_norm.to_csv(f"data_hub/{competition_name}_team_norm_data.csv", index = False)