In [ ]:
# file_aggregator
import csv, os
import shutil
import pandas as pd
import numpy as np
# fileDir = R'C:\Users\akash\Documents\Testing'
# fileOutput = R'C:\Users\akash\Documents\match_scouting_test.csv'
# fileEndDir = R'C:\Users\akash\Documents\endDir'
fileDir = R'C:\Users\Aztechs Robotics\Documents\Match Scouting Data'
fileOutput = R'C:\Users\Aztechs Robotics\Documents\schema.csv'
fileOutput_agg = R'C:\Users\Aztechs Robotics\Documents\match_scouting_2025_agg.csv'
fileOutput_radar = R'C:\Users\Aztechs Robotics\Documents\match_scouting_2025_radar.csv'
fileOutput_comp = R'C:\Users\Aztechs Robotics\Documents\match_scouting_2025_comp.csv'
fileEndDir = R'C:\Users\Aztechs Robotics\Documents\Previously Aggregated Scouting Data'

fileTest = R'C:\Users\Aztechs Robotics\Documents\match_scouting_2025_test.csv'

accepted_comps = {'', 'uvm', 'mayhem', 'battlecry', 'bc', 'minuteman'}
uvm = {69, 95, 157, 166, 237, 348, 811, 839, 1058, 1073, 1512, 1729, 2262, 2370, 2423, 2523, 3323, 
       4311, 4572, 4909, 5494, 5687, 6691, 6933, 7913, 8421, 8544, 9096, 9101, 10066, 10108, 10138, 10647}
mayhem = {131, 157, 166, 190, 319, 501, 1073, 1119, 1153, 1721, 1729, 1735, 1768, 1922, 2342, 2648, 
          3623, 3467, 3597, 5813, 5962, 6324, 8046, 9443}
bc = {48, 78, 88, 126, 131, 138, 151, 157, 166, 175, 177, 190, 238, 319, 467, 501, 694, 1058, 1073, 1100, 1155, 1277,
      1474, 1591, 1729, 1735, 1740, 1757, 1768, 1796, 2053, 2079, 2084, 2262, 2265, 2342, 2370, 2423, 2713, 2791, 
      2876, 2877, 3182, 3467, 4041, 4048, 4311, 4575, 4909, 5422, 5687, 6324, 6328, 7153, 7407, 8085, 8544, 8567, 8708,
      8724, 9443, 9642, 10063, 10229}
minuteman = {157, 175, 190, 663, 1071, 1099, 1119, 1735, 1768, 2064, 3182, 3464, 3467, 3566, 3623, 4169, 4905, 4909, 
             5347, 5422, 5902, 5962, 6328, 6620, 8013, 8708, 9644, 9729, 10063, 10393}



competition = input("Which competition to select? (Leave blank for all)").lower()




with open(fileOutput, 'a') as output:
    for entry in os.listdir(fileDir):
        filePath = fileDir + '\\'+ entry
        with open(filePath, "r") as file:
            data = ""
            data = file.read()
            output.write(data + "\n")
            file.close()
        shutil.move(filePath, fileEndDir)
    output.close()

data = pd.read_csv(fileOutput)

data['Auto'] = data['Auto #Scored Coral L1']*3 + data['Auto #Scored Coral L2']*4 + data['Auto #Scored Coral L3']*6 + data['Auto #Scored Coral L4']*7 + data['Auto #Scored Barge'] *4 + data['Auto #Scored Processor'] * 6 + data['Left Starting Position'] * 3
data['TeleopCoral'] = data['TeleOp #Scored Coral L1']*2 + data['TeleOp #Scored Coral L2']*3 + data['TeleOp #Scored Coral L3']*4 + data['TeleOp #Scored Coral L4']*5
data['TeleopAlgae'] = data['TeleOp #Scored Barge'] * 4 + data['TeleOp #Scored Processor'] * 2
# renaming data
# E.X. [T#SL1] = TeleOp Number Scored Coral L1
# E.X. [T#SP] = TeleOp Number Scored Barge
if(True):
    data['T#SL1'] = data['TeleOp #Scored Coral L1']
    data['T#SL2'] = data['TeleOp #Scored Coral L2']
    data['T#SL3'] = data['TeleOp #Scored Coral L3']
    data['T#SL4'] = data['TeleOp #Scored Coral L4']
    data['T#SB'] = data['TeleOp #Scored Barge']
    data['T#SP'] = data['TeleOp #Scored Processor']
    data['A#SL1'] = data['Auto #Scored Coral L1']
    data['A#SL2'] = data['Auto #Scored Coral L2']
    data['A#SL3'] = data['Auto #Scored Coral L3']
    data['A#SL4'] = data['Auto #Scored Coral L4']
    data['A#SB'] = data['Auto #Scored Barge']
    data['A#SP'] = data['Auto #Scored Processor']
    

    data['T#AL1'] = data['TeleOp #Attempted Coral L1']
    data['T#AL2'] = data['TeleOp #Attempted Coral L2']
    data['T#AL3'] = data['TeleOp #Attempted Coral L3']
    data['T#AL4'] = data['TeleOp #Attempted Coral L4']
    data['T#AB'] = data['TeleOp #Attempted Barge']
    data['T#AP'] = data['TeleOp #Attempted Processor']
    data['A#AL1'] = data['Auto #Attempted Coral L1']
    data['A#AL2'] = data['Auto #Attempted Coral L2']
    data['A#AL3'] = data['Auto #Attempted Coral L3']
    data['A#AL4'] = data['Auto #Attempted Coral L4']
    data['A#AB'] = data['Auto #Attempted Barge']
    data['A#AP'] = data['Auto #Attempted Processor']
    
mapping = {
    "Park": 2,
    "Hang Deep": 12,
    "Hang Shallow": 6
}
data["Endgame"] = data["Park/Shallow/Deep"].map(mapping).fillna(0).astype(int)

if(competition == 'uvm'):
    df_comp = data[data['Team Number'].isin(uvm)]
    print("Only UVM teams")
elif(competition == 'mayhem'):
    df_comp = data[data['Team Number'].isin(mayhem)]
    print("Only Mayhem teams")
elif(competition == 'battlecry' or competition == 'bc'):
    df_comp = data[data['Team Number'].isin(bc)]
    bc_copy = [x for x in bc if x not in data['Team Number'].tolist()]
    bc_copy.sort()
    print(bc_copy)
    print("Only Battlecry Teams")
else:
    df_comp = data
    print("All teams")



# df_comp.drop(inplace=True, columns=[col for col in df_comp.columns if '#Attempted' in col]+[col for col in df_comp.columns if '#Scored' in col])


col_to_drop = "Competition Location"
value_to_drop = "Test"
data_exclude_test = df_comp[~df_comp[col_to_drop].str.contains(value_to_drop, na=False)]
data_exclude_test.to_csv(fileOutput_comp)

# Match sheet data field
ms_df = data_exclude_test.groupby("Team Number")[["Auto", "TeleopCoral", "TeleopAlgae", "Endgame"] + [col for col in data_exclude_test.columns if 'A#' in col] + [col for col in data_exclude_test.columns if 'T#' in col]].mean(numeric_only=True).reset_index()


ms_df['Auto Score'] = ms_df['Auto']
# ms_df['Auto Acc'] = (ms_df['A#SL1']+ms_df['A#SL2']+ms_df['A#SL3']+ms_df['A#SL4']+ms_df["A#SP"]+ms_df['A#SB'])/(ms_df['A#AL1']+ms_df['A#AL2']+ms_df['A#AL3']+ms_df['A#AL4']+ms_df["A#AP"]+ms_df['A#AB'])
ms_df['Auto Coral'] = ms_df['A#SL1']*3+ms_df['A#SL2']*4+ms_df['A#SL3']*6+ms_df['A#SL4']*7
ms_df['Auto Algae'] = ms_df["A#SP"]*2+ms_df['A#SB']*4

ms_df['Teleop Score'] = ms_df['TeleopCoral'] + ms_df['TeleopAlgae']
ms_df['L1'] = ms_df['T#SL1']*2
ms_df['L2'] = ms_df['T#SL2']*3
ms_df['L3'] = ms_df['T#SL3']*4
ms_df['L4'] = ms_df['T#SL4']*5
ms_df['Processor'] = ms_df['T#SP']*2
ms_df['Barge'] = ms_df['T#SB']*4

ms_df['Endgame Score'] = ms_df['Endgame']
ms_df['Total Score'] = ms_df['Auto']+ms_df['TeleopCoral']+ms_df['TeleopAlgae']+ms_df['Endgame']

ms_df['AutoNorm'] = ms_df['Auto'] / ms_df['Auto'].max()
ms_df['L1Norm'] = ms_df['T#SL1'] / ms_df['T#SL1'].max()
ms_df['L2Norm'] = ms_df['T#SL2'] / ms_df['T#SL2'].max()
ms_df['L3Norm'] = ms_df['T#SL3'] / ms_df['T#SL3'].max()
ms_df['L4Norm'] = ms_df['T#SL4'] / ms_df['T#SL4'].max()
ms_df['TeleopAlgaeNorm'] = ms_df['TeleopAlgae'] / ms_df['TeleopAlgae'].max()
ms_df['EndgameNorm'] = ms_df['Endgame'] / ms_df['Endgame'].max()

ms_df['Auto Coral Acc'] = (ms_df['A#SL1']+ms_df['A#SL2']+ms_df['A#SL3']+ms_df['A#SL4'])/(ms_df['A#AL1']+ms_df['A#AL2']+ms_df['A#AL3']+ms_df['A#AL4'])
ms_df['Auto Algae Acc'] = (ms_df["A#SP"]+ms_df['A#SB'])/(ms_df["A#AP"]+ms_df['A#AB'])
ms_df['L1 Acc']=ms_df['T#SL1']/ms_df['T#AL1']
ms_df['L2 Acc']=ms_df['T#SL2']/ms_df['T#AL2']
ms_df['L3 Acc']=ms_df['T#SL3']/ms_df['T#AL3']
ms_df['L4 Acc']=ms_df['T#SL4']/ms_df['T#AL4']
ms_df['Processor Acc'] = ms_df['T#SP']/ms_df['T#AP']
ms_df['Barge Acc'] = ms_df['T#SB']/ms_df['T#AB']

ms_df.drop(columns=["Auto", "TeleopCoral", "TeleopAlgae", "Endgame"] + [col for col in data_exclude_test.columns if 'A#' in col] + [col for col in data_exclude_test.columns if 'T#' in col], inplace=True)
ms_df.replace(np.inf, 0, inplace=True)
ms_df.to_csv(fileOutput_agg)


# Radar Sheet Data Field
radar_norm = data_exclude_test.groupby("Team Number")[["Auto", "TeleopAlgae", "Endgame", "T#SL1", "T#SL2", "T#SL3", 
                                                       "T#SL4"]].mean().reset_index()
radar_norm['AutoNorm'] = radar_norm['Auto'] / radar_norm['Auto'].max()
radar_norm['L1'] = radar_norm['T#SL1'] / radar_norm['T#SL1'].max()
radar_norm['L2'] = radar_norm['T#SL2'] / radar_norm['T#SL2'].max()
radar_norm['L3'] = radar_norm['T#SL3'] / radar_norm['T#SL3'].max()
radar_norm['L4'] = radar_norm['T#SL4'] / radar_norm['T#SL4'].max()
radar_norm['TeleopAlgaeNorm'] = radar_norm['TeleopAlgae'] / radar_norm['TeleopAlgae'].max()
radar_norm['EndgameNorm'] = radar_norm['Endgame'] / radar_norm['Endgame'].max()

radar_norm.drop(columns=["Auto", "TeleopAlgae", "Endgame", "T#SL1", "T#SL2", "T#SL3", "T#SL4"], inplace=True)

radar_norm = radar_norm[['Team Number', 'TeleopAlgaeNorm','L1','L2','L3','L4','AutoNorm','EndgameNorm']]

radar_norm.to_csv(fileOutput_radar)


print ("Teams: " + str(len(radar_norm)))
print("Process Finished")

# Run only to clear data

In [68]:
import csv, os
import shutil
import pandas as pd
import numpy as np

ranier_dir = "/mnt/home/ranier-gran/Documents/Robotics/Scouting2026/"
ranier_dir = ""
# leo_dir = "C:\Users\every\StudioProjects\Scouting2026\schemas"

In [69]:
schema_path = ranier_dir + "schemas/"
full_df = pd.read_excel(schema_path + "Schema.xlsx")
full_df

Empty DataFrame
Columns: [Competition, randomNum, Scout, TeamNum, TeamColor, MatchNum, PreloadedFuel, StartingPos, AutoScored, AutoAccuracy, AutoPassed, AutoHang, TeleopScored, TeleopAccuracy, TeleopPassed, HangStatus, HangTime, AccuracyPos, OverBump, UnderTrench, PlayedDefense, CollectedFuel, PassedFuel, DidNothing, Other, Defense, StopReason, Rank, CommentsCNC]
Index: []

[0 rows x 29 columns]

In [70]:
match_csv_path = ranier_dir + "matchData/"
processed_csv_path = ranier_dir + "processedData/"

# Run each time you add data to your match data folder

In [71]:
match_data_dir = os.listdir(match_csv_path)
match_data_dir

['match_scouting_Battlecry_10063_27.csv',
 'match_scouting_Battlecry_10063_34.csv',
 'match_scouting_Battlecry_10262_12.csv',
 'match_scouting_Battlecry_10262_2.csv',
 'match_scouting_Battlecry_10262_33.csv',
 'match_scouting_Battlecry_10262_54.csv',
 'match_scouting_Battlecry_10262_59.csv',
 'match_scouting_Battlecry_10910_35.csv',
 'match_scouting_Battlecry_11175_1.csv',
 'match_scouting_Battlecry_11175_18.csv',
 'match_scouting_Battlecry_1155_11.csv',
 'match_scouting_Battlecry_1155_35.csv',
 'match_scouting_Battlecry_126_28.csv',
 'match_scouting_Battlecry_126_35.csv',
 'match_scouting_Battlecry_1277_15.csv',
 'match_scouting_Battlecry_1277_32.csv',
 'match_scouting_Battlecry_131_30.csv',
 'match_scouting_Battlecry_131_8.csv',
 'match_scouting_Battlecry_1474_12.csv',
 'match_scouting_Battlecry_1474_30.csv',
 'match_scouting_Battlecry_151_28.csv',
 'match_scouting_Battlecry_151_33.csv',
 'match_scouting_Battlecry_157_10.csv',
 'match_scouting_Battlecry_157_33.csv',
 'match_scouting_Battlecry_157_4.csv',
 'match_scouting_Battlecry_157_56.csv',
 'match_scouting_Battlecry_1591_2.csv',
 'match_scouting_Battlecry_1591_9.csv',
 'match_scouting_Battlecry_166_24.csv',
 'match_scouting_Battlecry_166_32.csv',
 'match_scouting_Battlecry_166_55.csv',
 'match_scouting_Battlecry_166_6.csv',
 'match_scouting_Battlecry_1729_13.csv',
 'match_scouting_Battlecry_1729_31.csv',
 'match_scouting_Battlecry_1735_13.csv',
 'match_scouting_Battlecry_1735_34.csv',
 'match_scouting_Battlecry_1735_8.csv',
 'match_scouting_Battlecry_173_5.csv',
 'match_scouting_Battlecry_1768_1.csv',
 'match_scouting_Battlecry_1768_35.csv',
 'match_scouting_Battlecry_1768_56.csv',
 'match_scouting_Battlecry_190_24.csv',
 'match_scouting_Battlecry_190_31.csv',
 'match_scouting_Battlecry_190_59.csv',
 'match_scouting_Battlecry_190_7.csv',
 'match_scouting_Battlecry_1922_11.csv',
 'match_scouting_Battlecry_1922_2.csv',
 'match_scouting_Battlecry_2262_27.csv',
 'match_scouting_Battlecry_2262_54.csv',
 'match_scouting_Battlecry_2265_13.csv',
 'match_scouting_Battlecry_2265_28.csv',
 'match_scouting_Battlecry_2342_29.csv',
 'match_scouting_Battlecry_2342_3.csv',
 'match_scouting_Battlecry_2370_3.csv',
 'match_scouting_Battlecry_2370_31.csv',
 'match_scouting_Battlecry_2370_55.csv',
 'match_scouting_Battlecry_238_25.csv',
 'match_scouting_Battlecry_238_3.csv',
 'match_scouting_Battlecry_238_33.csv',
 'match_scouting_Battlecry_2423_29.csv',
 'match_scouting_Battlecry_2423_34.csv',
 'match_scouting_Battlecry_271_9.csv',
 'match_scouting_Battlecry_3461_30.csv',
 'match_scouting_Battlecry_3461_60.csv',
 'match_scouting_Battlecry_3461_8.csv',
 'match_scouting_Battlecry_41222_1.csv',
 'match_scouting_Battlecry_4122_12.csv',
 'match_scouting_Battlecry_4122_31.csv',
 'match_scouting_Battlecry_4122_57.csv',
 'match_scouting_Battlecry_4176_11.csv',
 'match_scouting_Battlecry_4546_10.csv',
 'match_scouting_Battlecry_4546_3.csv',
 'match_scouting_Battlecry_4575_11.csv',
 'match_scouting_Battlecry_4575_31.csv',
 'match_scouting_Battlecry_4575_60.csv',
 'match_scouting_Battlecry_467_15.csv',
 'match_scouting_Battlecry_467_30.csv',
 'match_scouting_Battlecry_467_35.csv',
 'match_scouting_Battlecry_467_5.csv',
 'match_scouting_Battlecry_48_13.csv',
 'match_scouting_Battlecry_48_3.csv',
 'match_scouting_Battlecry_516_29.csv',
 'match_scouting_Battlecry_5494_1.csv',
 'match_scouting_Battlecry_5494_32.csv',
 'match_scouting_Battlecry_5735_12.csv',
 'match_scouting_Battlecry_5735_25.csv',
 'match_scouting_Battlecry_5735_34.csv',
 'match_scouting_Battlecry_5735_7.csv',
 'match_scouting_Battlecry_5813_16.csv',
 'match_scouting_Battlecry_6153_10.csv',
 'match_scouting_Battlecry_6731_26.csv',
 'match_scouting_Battlecry_6731_33.csv',
 'match_scouting_Battlecry_6731_8.csv',
 'match_scouting_Battlecry_6933_17.csv',
 'match_scouting_Battlecry_6933_32.csv',
 'match_scouting_Battlecry_6933_6.csv',
 'match_scouting_Battlecry_694_12.csv',
 'match_scouting_Battlecry_694_36.csv',
 'match_scouting_Battlecry_7153_32.csv',
 'match_scouting_Battlecry_7153_6.csv',
 'match_scouting_Battlecry_8085_13.csv',
 'match_scouting_Battlecry_8085_26.csv',
 'match_scouting_Battlecry_8085_36.csv',
 'match_scouting_Battlecry_8544_10.csv',
 'match_scouting_Battlecry_8544_36.csv',
 'match_scouting_Battlecry_8544_59.csv',
 'match_scouting_Battlecry_8567_57.csv',
 'match_scouting_Battlecry_8567_9.csv',
 'match_scouting_Battlecry_8708_10.csv',
 'match_scouting_Battlecry_8708_32.csv',
 'match_scouting_Battlecry_8724_2.csv',
 'match_scouting_Battlecry_8724_31.csv',
 'match_scouting_Battlecry_8724_36.csv',
 'match_scouting_Battlecry_8724_60.csv',
 'match_scouting_Battlecry_8724_9.csv',
 'match_scouting_Battlecry_9990_34.csv']

In [72]:
def process_match_sheet(full_df, match_csv_path, sheet_name):
    match_df = pd.read_csv(match_csv_path + sheet_name, header = None)
    match_df.drop(29, axis=1, inplace=True)
    match_df.columns = full_df.columns
    full_df = pd.concat([full_df, match_df], ignore_index = True)
    return full_df

In [73]:
for file_name in match_data_dir:
    full_df = process_match_sheet(full_df, match_csv_path, file_name)
    shutil.move(match_csv_path + file_name, processed_csv_path + file_name)
full_df

,Competition,randomNum,Scout,TeamNum,TeamColor,MatchNum,PreloadedFuel,StartingPos,AutoScored,AutoAccuracy,...,UnderTrench,PlayedDefense,CollectedFuel,PassedFuel,DidNothing,Other,Defense,StopReason,Rank,CommentsCNC
0,Battlecry,1,Reagan,10063,Red,27,True,Position 2,NaN,Less Than 10%,...,True,True,False,True,False,False,No Defense,Not stopped,Rank 3,NaN
1,Battlecry,1,Becky,10063,Red,34,True,Position 2,NaN,50%,...,True,True,False,True,False,False,Light Defense,Not stopped,Rank 3,passed by primarily pushing instead of throwing
2,Battlecry,1,Saaam,10262,Blue,12,True,Position 1,NaN,50%,...,False,True,True,False,False,False,No Defense,Not stopped,Rank 2,stuck on bump during auto
3,Battlecry,1,Keegan,10262,Red,2,False,Position 2,10,75%,...,False,False,False,True,False,False,No Defense,Not stopped,Rank 3,NaN
4,Battlecry,1,Lweo,10262,Blue,33,True,Position 2,8,75%,...,False,False,True,True,False,False,No Defense,Not stopped,Rank 1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,Battlecry,1,Lweo,8724,Red,31,True,Position 2,10,75%,...,True,False,True,True,False,False,Light Defense,Not stopped,Rank 2,NaN
112,Battlecry,1,Rob,8724,Blue,36,True,Position 2,18,More than 95%,...,True,False,True,True,False,False,No Defense,Not stopped,Rank 2,75% accuracy (I forgot oops)
113,Battlecry,1,Julia,8724,Red,60,True,Position 3,15,75%,...,True,False,True,False,False,False,Light Defense,Not stopped,Rank 1,NaN
114,Battlecry,1,Saaam,8724,Blue,9,True,Position 1,20,50%,...,True,False,True,False,False,False,Light Defense,Not stopped,Rank 2,NaN
115,Battlecry,1,Reagan,9990,Blue,34,True,Position 1,NaN,Less Than 10%,...,True,False,True,False,False,False,No Defense,Not stopped,Rank 1,NaN

In [74]:
full_df_dummies = full_df.copy()
full_df_dummies['AutoAccuracyNum'] = full_df_dummies['AutoAccuracy'].str[-3:-1].astype(float)/100
full_df_dummies['TeleopAccuracyNum'] = full_df_dummies['TeleopAccuracy'].str[-3:-1].astype(float)/100
columns_to_encode = ['AutoHang','HangStatus','AccuracyPos','OverBump','UnderTrench','PlayedDefense','CollectedFuel','PassedFuel','DidNothing','Other','Defense','StopReason']
full_dummies_df = pd.get_dummies(full_df_dummies, columns=columns_to_encode)
print("\nEncoded DataFrame:")
full_dummies_df

Encoded DataFrame:

,Competition,randomNum,Scout,TeamNum,TeamColor,MatchNum,PreloadedFuel,StartingPos,AutoScored,AutoAccuracy,...,DidNothing_False,DidNothing_True,Other_False,Other_True,Defense_Heavy Defense,Defense_Light Defense,Defense_No Defense,StopReason_Not stopped,StopReason_Physically Broke,StopReason_Tipped
0,Battlecry,1,Reagan,10063,Red,27,True,Position 2,NaN,Less Than 10%,...,True,False,True,False,False,False,True,True,False,False
1,Battlecry,1,Becky,10063,Red,34,True,Position 2,NaN,50%,...,True,False,True,False,False,True,False,True,False,False
2,Battlecry,1,Saaam,10262,Blue,12,True,Position 1,NaN,50%,...,True,False,True,False,False,False,True,True,False,False
3,Battlecry,1,Keegan,10262,Red,2,False,Position 2,10,75%,...,True,False,True,False,False,False,True,True,False,False
4,Battlecry,1,Lweo,10262,Blue,33,True,Position 2,8,75%,...,True,False,True,False,False,False,True,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,Battlecry,1,Lweo,8724,Red,31,True,Position 2,10,75%,...,True,False,True,False,False,True,False,True,False,False
112,Battlecry,1,Rob,8724,Blue,36,True,Position 2,18,More than 95%,...,True,False,True,False,False,False,True,True,False,False
113,Battlecry,1,Julia,8724,Red,60,True,Position 3,15,75%,...,True,False,True,False,False,True,False,True,False,False
114,Battlecry,1,Saaam,8724,Blue,9,True,Position 1,20,50%,...,True,False,True,False,False,True,False,True,False,False
115,Battlecry,1,Reagan,9990,Blue,34,True,Position 1,NaN,Less Than 10%,...,True,False,True,False,False,False,True,True,False,False

In [75]:
full_dummies_df.to_csv("data_hub/match_data_hub.csv", index=False)

In [76]:
match_data_dir = os.listdir(match_csv_path)
match_data_dir

[]

In [77]:
competition_dict = {
    "UVM": {
        "Week": 4, 
        "Teams": [157, 190, 1100, 175, 75, 88, 6328],
    },
    "WPI": {
        "Week": 5,
        "Teams": [97, 157, 190, 237, 348, 467, 716, 999, 1027, 
                 1100, 1474, 1740, 1757, 1768, 2079, 2168, 2262,
                 2370, 3205, 3467, 3634, 4048, 4628, 5000, 5112,
                 5347, 5422, 5491, 5494, 6333, 6762, 7760, 8544, 
                 8567, 8724, 9644, 10254, 10393, 11483],
    },
    "Battlecry": {
        "Week": 12,
        "Teams": [48, 126, 131, 151, 157, 166, 173, 190, 238, 271, 
                 467, 516, 694, 1155, 1277, 1474, 1591, 1729, 1735, 
                 1768, 1922, 2262, 2265, 2342, 2370, 2423, 3461, 
                 4122, 4176, 4546, 4575, 5494, 5735, 5813, 6153, 
                 6731, 6933, 7153, 8085, 8544, 8567, 8708, 8724, 
                 9990, 10063, 10262, 10910, 11175],
    },
    "Minuteman": {
        "Week": 1,
        "Teams": [157, 175, 663, 1071, 1099, 1119, 1735, 1768,
                 2064, 3182, 3464, 3467, 3566, 3623, 4169, 4905,
                 4909, 5347, 5422, 5902, 5962, 6328, 6620, 8013, 
                 8708, 9644, 9729, 10063, 10393]
    },
}
competition_dict

{'UVM': {'Week': 4, 'Teams': [157, 190, 1100, 175, 75, 88, 6328]},
 'WPI': {'Week': 5,
  'Teams': [97,
   157,
   190,
   237,
   348,
   467,
   716,
   999,
   1027,
   1100,
   1474,
   1740,
   1757,
   1768,
   2079,
   2168,
   2262,
   2370,
   3205,
   3467,
   3634,
   4048,
   4628,
   5000,
   5112,
   5347,
   5422,
   5491,
   5494,
   6333,
   6762,
   7760,
   8544,
   8567,
   8724,
   9644,
   10254,
   10393,
   11483]},
 'Battlecry': {'Week': 12,
  'Teams': [48,
   126,
   131,
   151,
   157,
   166,
   173,
   190,
   238,
   271,
   467,
   516,
   694,
   1155,
   1277,
   1474,
   1591,
   1729,
   1735,
   1768,
   1922,
   2262,
   2265,
   2342,
   2370,
   2423,
   3461,
   4122,
   4176,
   4546,
   4575,
   5494,
   5735,
   5813,
   6153,
   6731,
   6933,
   7153,
   8085,
   8544,
   8567,
   8708,
   8724,
   9990,
   10063,
   10262,
   10910,
   11175]},
 'Minuteman': {'Week': 1,
  'Teams': [157,
   175,
   663,
   1071,
   1099,
   1119,
   1735,
   1768,
   2064,
   3182,
   3464,
   3467,
   3566,
   3623,
   4169,
   4905,
   4909,
   5347,
   5422,
   5902,
   5962,
   6328,
   6620,
   8013,
   8708,
   9644,
   9729,
   10063,
   10393]}}

In [78]:
competition_name = 'Battlecry'
competition_df = full_dummies_df[full_dummies_df['TeamNum'].isin(competition_dict[competition_name]['Teams'])]
competition_df

,Competition,randomNum,Scout,TeamNum,TeamColor,MatchNum,PreloadedFuel,StartingPos,AutoScored,AutoAccuracy,...,DidNothing_False,DidNothing_True,Other_False,Other_True,Defense_Heavy Defense,Defense_Light Defense,Defense_No Defense,StopReason_Not stopped,StopReason_Physically Broke,StopReason_Tipped
0,Battlecry,1,Reagan,10063,Red,27,True,Position 2,NaN,Less Than 10%,...,True,False,True,False,False,False,True,True,False,False
1,Battlecry,1,Becky,10063,Red,34,True,Position 2,NaN,50%,...,True,False,True,False,False,True,False,True,False,False
2,Battlecry,1,Saaam,10262,Blue,12,True,Position 1,NaN,50%,...,True,False,True,False,False,False,True,True,False,False
3,Battlecry,1,Keegan,10262,Red,2,False,Position 2,10,75%,...,True,False,True,False,False,False,True,True,False,False
4,Battlecry,1,Lweo,10262,Blue,33,True,Position 2,8,75%,...,True,False,True,False,False,False,True,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,Battlecry,1,Lweo,8724,Red,31,True,Position 2,10,75%,...,True,False,True,False,False,True,False,True,False,False
112,Battlecry,1,Rob,8724,Blue,36,True,Position 2,18,More than 95%,...,True,False,True,False,False,False,True,True,False,False
113,Battlecry,1,Julia,8724,Red,60,True,Position 3,15,75%,...,True,False,True,False,False,True,False,True,False,False
114,Battlecry,1,Saaam,8724,Blue,9,True,Position 1,20,50%,...,True,False,True,False,False,True,False,True,False,False
115,Battlecry,1,Reagan,9990,Blue,34,True,Position 1,NaN,Less Than 10%,...,True,False,True,False,False,False,True,True,False,False

In [79]:
competition_df.columns

Index(['Competition', 'randomNum', 'Scout', 'TeamNum', 'TeamColor', 'MatchNum',
       'PreloadedFuel', 'StartingPos', 'AutoScored', 'AutoAccuracy',
       'AutoPassed', 'TeleopScored', 'TeleopAccuracy', 'TeleopPassed',
       'HangTime', 'Rank', 'CommentsCNC', 'AutoAccuracyNum',
       'TeleopAccuracyNum', 'AutoHang_False', 'AccuracyPos_About the same',
       'AccuracyPos_Consistently bad accuracy', 'AccuracyPos_When moving',
       'AccuracyPos_When unmoving', 'OverBump_False', 'OverBump_True',
       'UnderTrench_False', 'UnderTrench_True', 'PlayedDefense_False',
       'PlayedDefense_True', 'CollectedFuel_False', 'CollectedFuel_True',
       'PassedFuel_False', 'PassedFuel_True', 'DidNothing_False',
       'DidNothing_True', 'Other_False', 'Other_True', 'Defense_Heavy Defense',
       'Defense_Light Defense', 'Defense_No Defense', 'StopReason_Not stopped',
       'StopReason_Physically Broke', 'StopReason_Tipped'],
      dtype='object')

In [88]:
for i, val in enumerate(competition_df['AutoScored']):
    print(competition_df.index[i])
    print(val)
# competition_df.drop(26, inplace = True)

0
nan
1
nan
2
nan
3
10
4
8
5
20
6
nan
7
nan
8
18
9
3
10
nan
11
5
12
7
14
10
15
12
16
nan
17
20
18
10
19
nan
20
7
21
10
22
20
23
10
24
23
25
0
27
55
28
2
29
40
30
30
31
0
32
nan
33
nan
34
nan
35
6
36
7
37
nan
38
30
39
70
40
70
41
nan
42
15
43
20
44
nan
45
15
46
25
47
2
48
7
49
3
50
8
51
20
52
20
53
20
54
20
55
28
56
nan
57
nan
58
nan
59
15
60
nan
61
8
62
nan
63
nan
66
15
67
10
68
nan
69
nan
70
0
71
nan
72
nan
73
10
74
nan
75
35
76
18
77
nan
78
8
79
15
80
20
81
nan
82
4
83
8
84
10
85
nan
86
2
87
5
88
20
89
8
90
nan
91
nan
92
1
93
60
94
nan
95
9
96
70
97
0
98
nan
99
20
100
25
101
15
102
nan
103
10
104
8
105
7
106
11
107
nan
108
10
109
15
110
20
111
10
112
18
113
15
114
20
115
nan

In [89]:
for col in competition_df.columns:
    if col not in ['TeamNum','MatchNum','randomNum', 'PreloadedFuel', 'CommentsCNC']:
        try:
            competition_df[col] = competition_df[col].astype('float64') # Convert to float64
        except:
            print(f"Could not convert column '{col}' to float64")
if "HangStatus_Level 1" not in competition_df.columns:
    competition_df['HangStatus_Level 1'] = 0
if "HangStatus_Level 2" not in competition_df.columns:
    competition_df['HangStatus_Level 2'] = 0
if "HangStatus_Level 3" not in competition_df.columns:
    competition_df['HangStatus_Level 3'] = 0
if "AutoHang_True" not in competition_df.columns:
    competition_df['AutoHang_True'] = 0

Could not convert column 'Competition' to float64
Could not convert column 'Scout' to float64
Could not convert column 'TeamColor' to float64
Could not convert column 'StartingPos' to float64
Could not convert column 'AutoAccuracy' to float64
Could not convert column 'TeleopAccuracy' to float64
Could not convert column 'Rank' to float64

C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64
C:\Users\every\AppData\Local\Temp\ipykernel_48628\300723034.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_df[col] = competition_df[col].astype('float64') # Convert to float64

In [90]:
competition_df.to_csv(f"data_hub/{competition_name}_team_match_data.csv", index = False)

In [91]:
competition_aggregate = competition_df.groupby('TeamNum').mean(numeric_only=True).reset_index()
competition_aggregate['TeleopHangTotal'] = competition_aggregate['HangStatus_Level 1'] * 10 + competition_aggregate['HangStatus_Level 2'] * 20 + competition_aggregate['HangStatus_Level 3'] * 30
competition_aggregate['AutoHangTotal'] = competition_aggregate['AutoHang_True'] * 15
competition_aggregate['HangTotal'] = competition_aggregate['AutoHangTotal'] + competition_aggregate['TeleopHangTotal']
competition_aggregate['PassedTotal'] = competition_aggregate['AutoPassed'] + competition_aggregate['TeleopPassed']
competition_aggregate

,TeamNum,AutoScored,AutoPassed,TeleopScored,TeleopPassed,HangTime,AutoAccuracyNum,TeleopAccuracyNum,AutoHang_False,AccuracyPos_About the same,...,StopReason_Physically Broke,StopReason_Tipped,HangStatus_Level 1,HangStatus_Level 2,HangStatus_Level 3,AutoHang_True,TeleopHangTotal,AutoHangTotal,HangTotal,PassedTotal
0,48,17.500000,NaN,67.500000,12.500000,0.0,0.950000,0.950000,1.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1,126,7.000000,NaN,48.000000,0.000000,0.0,0.750000,0.500000,1.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2,131,20.000000,NaN,82.500000,12.500000,0.0,0.525000,0.950000,1.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,151,8.500000,NaN,33.000000,20.000000,0.0,0.500000,0.750000,1.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
4,157,13.250000,1.0,74.750000,28.250000,0.0,0.787500,0.675000,1.0,0.250000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29.250000
5,166,18.000000,0.0,131.500000,53.750000,0.0,0.562500,0.625000,1.0,0.250000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,53.750000
6,173,NaN,NaN,20.000000,0.000000,0.0,0.100000,0.250000,1.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
7,190,17.500000,NaN,46.500000,11.250000,0.0,0.425000,0.883333,1.0,0.250000,...,0.250000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
8,238,NaN,NaN,32.666667,15.000000,0.0,0.383333,0.600000,1.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
9,271,8.000000,NaN,52.000000,0.000000,0.0,0.500000,0.750000,1.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
10,467,20.333333,NaN,28.750000,10.000000,0.0,0.737500,0.733333,1.0,0.250000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
11,516,NaN,NaN,105.000000,20.000000,0.0,0.100000,0.750000,1.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
12,694,35.000000,NaN,190.000000,37.500000,0.0,0.525000,0.950000,1.0,0.500000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
13,1155,5.000000,NaN,24.000000,0.000000,0.0,0.425000,0.725000,1.0,0.000000,...,0.000000,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
14,1277,11.000000,NaN,51.000000,0.000000,0.0,0.750000,0.625000,1.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
15,1474,10.000000,5.0,0.500000,0.000000,0.0,0.300000,0.175000,1.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.000000
16,1591,55.000000,NaN,40.000000,0.000000,0.0,0.500000,0.500000,1.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
17,1729,NaN,NaN,70.000000,0.000000,0.0,0.100000,0.750000,1.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
18,1735,6.500000,NaN,0.000000,15.000000,0.0,0.600000,0.950000,1.0,0.333333,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
19,1768,56.666667,NaN,160.000000,86.666667,0.0,0.950000,0.950000,1.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
20,1922,20.000000,NaN,105.000000,5.000000,0.0,0.950000,0.725000,1.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
21,2262,4.500000,NaN,0.500000,0.000000,0.0,0.625000,0.500000,1.0,0.500000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
22,2265,5.500000,NaN,0.000000,0.000000,0.0,0.850000,0.500000,1.0,0.500000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
23,2342,20.000000,NaN,55.000000,0.000000,0.0,0.100000,0.950000,1.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
24,2370,22.666667,5.0,143.333333,40.000000,0.0,0.816667,0.950000,1.0,1.000000,...,0.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45.000000
25,2423,15.000000,NaN,63.500000,0.000000,0.0,0.375000,0.750000,1.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
26,3461,NaN,NaN,15.000000,0.000000,0.0,0.300000,0.625000,1.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
27,4122,12.500000,NaN,108.333333,36.666667,0.0,0.733333,0.950000,1.0,0.333333,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
28,4176,NaN,NaN,0.000000,0.000000,0.0,0.500000,0.500000,1.0,1.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
29,4546,0.000000,NaN,15.000000,0.000000,0.0,0.100000,0.500000,1.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
30,4575,10.000000,NaN,22.333333,8.333333,0.0,0.450000,0.583333,1.0,0.666667,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
31,5494,6.000000,NaN,2.500000,0.000000,0.0,0.600000,0.175000,1.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
32,5735,5.666667,10.0,12.750000,31.250000,0.0,0.237500,0.366667,1.0,0.250000,...,0.250000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,41.250000
33,5813,20.000000,NaN,140.000000,10.000000,0.0,0.750000,0.750000,1.0,1.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
34,6153,8.000000,NaN,0.000000,0.000000,0.0,0.750000,NaN,1.0,1.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
35,6731,1.000000,NaN,13.333333,28.333333,0.0,0.233333,0.383333,1.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
36,6933,34.500000,40.0,32.000000,43.333333,0.0,0.733333,0.500000,1.0,0.333333,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,83.333333
37,7153,20.000000,0.0,0.000000,0.000000,0.0,0.500000,0.500000,1.0,1.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
38,8085,20.000000,NaN,68.333333,26.666667,0.0,0.666667,0.883333,1.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
39,8544,8.333333,0.0,59.666667,8.000000,0.0,0.583333,0.816667,1.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.000000
40,8567,11.000000,NaN,27.500000,3.500000,0.0,0.175000,0.625000,1.0,0.500000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
41,8708,12.500000,NaN,25.000000,5.000000,0.0,0.850000,0.950000,1.0,0.000000,...,0.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
42,8724,16.600000,NaN,61.800000,15.400000,0.0,0.780000,0.787500,1.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
43,9990,NaN,NaN,132.000000,0.000000,0.0,0.100000,0.950000,1.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
44,10063,NaN,NaN,0.000000,5.000000,0.0,0.300000,0.500000,1.0,0.500000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
45,10262,12.666667,NaN,47.000000,6.000000,0.0,0.780000,0.750000,1.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
46,10910,NaN,NaN,0.000000,15.000000,0.0,0.500000,NaN,1.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
47,11175,10.500000,NaN,0.000000,0.000000,0.0,0.850000,NaN,1.0,0.000000,...,0.000000,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN

In [92]:
competition_aggregate.columns

Index(['TeamNum', 'AutoScored', 'AutoPassed', 'TeleopScored', 'TeleopPassed',
       'HangTime', 'AutoAccuracyNum', 'TeleopAccuracyNum', 'AutoHang_False',
       'AccuracyPos_About the same', 'AccuracyPos_Consistently bad accuracy',
       'AccuracyPos_When moving', 'AccuracyPos_When unmoving',
       'OverBump_False', 'OverBump_True', 'UnderTrench_False',
       'UnderTrench_True', 'PlayedDefense_False', 'PlayedDefense_True',
       'CollectedFuel_False', 'CollectedFuel_True', 'PassedFuel_False',
       'PassedFuel_True', 'DidNothing_False', 'DidNothing_True', 'Other_False',
       'Other_True', 'Defense_Heavy Defense', 'Defense_Light Defense',
       'Defense_No Defense', 'StopReason_Not stopped',
       'StopReason_Physically Broke', 'StopReason_Tipped',
       'HangStatus_Level 1', 'HangStatus_Level 2', 'HangStatus_Level 3',
       'AutoHang_True', 'TeleopHangTotal', 'AutoHangTotal', 'HangTotal',
       'PassedTotal'],
      dtype='object')

In [93]:
competition_aggregate.to_csv(f"data_hub/{competition_name}_team_aggregate_data.csv", index = False)

In [94]:
competition_norm = competition_aggregate[['TeamNum', 'AutoScored','AutoPassed','TeleopScored','TeleopPassed', 'PassedTotal', 'HangTotal']]
competition_norm['AutoScoredNorm'] = competition_norm['AutoScored'] / competition_norm['AutoScored'].max()
competition_norm['AutoPassedNorm'] = competition_norm['AutoPassed'] / competition_norm['AutoPassed'].max()
competition_norm['TeleopScoredNorm'] = competition_norm['TeleopScored'] / competition_norm['TeleopScored'].max()
competition_norm['TeleopPassedNorm'] = competition_norm['TeleopPassed'] / competition_norm['TeleopPassed'].max()
competition_norm['PassedTotalNorm'] = competition_norm['PassedTotal'] / competition_norm['PassedTotal'].max()
competition_norm['HangTotalNorm'] = competition_norm['HangTotal'] / competition_norm['HangTotal'].max()
competition_norm

C:\Users\every\AppData\Local\Temp\ipykernel_48628\2039474675.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_norm['AutoScoredNorm'] = competition_norm['AutoScored'] / competition_norm['AutoScored'].max()
C:\Users\every\AppData\Local\Temp\ipykernel_48628\2039474675.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_norm['AutoPassedNorm'] = competition_norm['AutoPassed'] / competition_norm['AutoPassed'].max()
C:\Users\every\AppData\Local\Temp\ipykernel_48628\2039474675.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_norm['TeleopScoredNorm'] = competition_norm['TeleopScored'] / competition_norm['TeleopScored'].max()
C:\Users\every\AppData\Local\Temp\ipykernel_48628\2039474675.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_norm['TeleopPassedNorm'] = competition_norm['TeleopPassed'] / competition_norm['TeleopPassed'].max()
C:\Users\every\AppData\Local\Temp\ipykernel_48628\2039474675.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_norm['PassedTotalNorm'] = competition_norm['PassedTotal'] / competition_norm['PassedTotal'].max()
C:\Users\every\AppData\Local\Temp\ipykernel_48628\2039474675.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  competition_norm['HangTotalNorm'] = competition_norm['HangTotal'] / competition_norm['HangTotal'].max()

,TeamNum,AutoScored,AutoPassed,TeleopScored,TeleopPassed,PassedTotal,HangTotal,AutoScoredNorm,AutoPassedNorm,TeleopScoredNorm,TeleopPassedNorm,PassedTotalNorm,HangTotalNorm
0,48,17.500000,NaN,67.500000,12.500000,NaN,0.0,0.308824,NaN,0.355263,0.144231,NaN,NaN
1,126,7.000000,NaN,48.000000,0.000000,NaN,0.0,0.123529,NaN,0.252632,0.000000,NaN,NaN
2,131,20.000000,NaN,82.500000,12.500000,NaN,0.0,0.352941,NaN,0.434211,0.144231,NaN,NaN
3,151,8.500000,NaN,33.000000,20.000000,NaN,0.0,0.150000,NaN,0.173684,0.230769,NaN,NaN
4,157,13.250000,1.0,74.750000,28.250000,29.250000,0.0,0.233824,0.025,0.393421,0.325962,0.351,NaN
5,166,18.000000,0.0,131.500000,53.750000,53.750000,0.0,0.317647,0.000,0.692105,0.620192,0.645,NaN
6,173,NaN,NaN,20.000000,0.000000,NaN,0.0,NaN,NaN,0.105263,0.000000,NaN,NaN
7,190,17.500000,NaN,46.500000,11.250000,NaN,0.0,0.308824,NaN,0.244737,0.129808,NaN,NaN
8,238,NaN,NaN,32.666667,15.000000,NaN,0.0,NaN,NaN,0.171930,0.173077,NaN,NaN
9,271,8.000000,NaN,52.000000,0.000000,NaN,0.0,0.141176,NaN,0.273684,0.000000,NaN,NaN
10,467,20.333333,NaN,28.750000,10.000000,NaN,0.0,0.358824,NaN,0.151316,0.115385,NaN,NaN
11,516,NaN,NaN,105.000000,20.000000,NaN,0.0,NaN,NaN,0.552632,0.230769,NaN,NaN
12,694,35.000000,NaN,190.000000,37.500000,NaN,0.0,0.617647,NaN,1.000000,0.432692,NaN,NaN
13,1155,5.000000,NaN,24.000000,0.000000,NaN,0.0,0.088235,NaN,0.126316,0.000000,NaN,NaN
14,1277,11.000000,NaN,51.000000,0.000000,NaN,0.0,0.194118,NaN,0.268421,0.000000,NaN,NaN
15,1474,10.000000,5.0,0.500000,0.000000,5.000000,0.0,0.176471,0.125,0.002632,0.000000,0.060,NaN
16,1591,55.000000,NaN,40.000000,0.000000,NaN,0.0,0.970588,NaN,0.210526,0.000000,NaN,NaN
17,1729,NaN,NaN,70.000000,0.000000,NaN,0.0,NaN,NaN,0.368421,0.000000,NaN,NaN
18,1735,6.500000,NaN,0.000000,15.000000,NaN,0.0,0.114706,NaN,0.000000,0.173077,NaN,NaN
19,1768,56.666667,NaN,160.000000,86.666667,NaN,0.0,1.000000,NaN,0.842105,1.000000,NaN,NaN
20,1922,20.000000,NaN,105.000000,5.000000,NaN,0.0,0.352941,NaN,0.552632,0.057692,NaN,NaN
21,2262,4.500000,NaN,0.500000,0.000000,NaN,0.0,0.079412,NaN,0.002632,0.000000,NaN,NaN
22,2265,5.500000,NaN,0.000000,0.000000,NaN,0.0,0.097059,NaN,0.000000,0.000000,NaN,NaN
23,2342,20.000000,NaN,55.000000,0.000000,NaN,0.0,0.352941,NaN,0.289474,0.000000,NaN,NaN
24,2370,22.666667,5.0,143.333333,40.000000,45.000000,0.0,0.400000,0.125,0.754386,0.461538,0.540,NaN
25,2423,15.000000,NaN,63.500000,0.000000,NaN,0.0,0.264706,NaN,0.334211,0.000000,NaN,NaN
26,3461,NaN,NaN,15.000000,0.000000,NaN,0.0,NaN,NaN,0.078947,0.000000,NaN,NaN
27,4122,12.500000,NaN,108.333333,36.666667,NaN,0.0,0.220588,NaN,0.570175,0.423077,NaN,NaN
28,4176,NaN,NaN,0.000000,0.000000,NaN,0.0,NaN,NaN,0.000000,0.000000,NaN,NaN
29,4546,0.000000,NaN,15.000000,0.000000,NaN,0.0,0.000000,NaN,0.078947,0.000000,NaN,NaN
30,4575,10.000000,NaN,22.333333,8.333333,NaN,0.0,0.176471,NaN,0.117544,0.096154,NaN,NaN
31,5494,6.000000,NaN,2.500000,0.000000,NaN,0.0,0.105882,NaN,0.013158,0.000000,NaN,NaN
32,5735,5.666667,10.0,12.750000,31.250000,41.250000,0.0,0.100000,0.250,0.067105,0.360577,0.495,NaN
33,5813,20.000000,NaN,140.000000,10.000000,NaN,0.0,0.352941,NaN,0.736842,0.115385,NaN,NaN
34,6153,8.000000,NaN,0.000000,0.000000,NaN,0.0,0.141176,NaN,0.000000,0.000000,NaN,NaN
35,6731,1.000000,NaN,13.333333,28.333333,NaN,0.0,0.017647,NaN,0.070175,0.326923,NaN,NaN
36,6933,34.500000,40.0,32.000000,43.333333,83.333333,0.0,0.608824,1.000,0.168421,0.500000,1.000,NaN
37,7153,20.000000,0.0,0.000000,0.000000,0.000000,0.0,0.352941,0.000,0.000000,0.000000,0.000,NaN
38,8085,20.000000,NaN,68.333333,26.666667,NaN,0.0,0.352941,NaN,0.359649,0.307692,NaN,NaN
39,8544,8.333333,0.0,59.666667,8.000000,8.000000,0.0,0.147059,0.000,0.314035,0.092308,0.096,NaN
40,8567,11.000000,NaN,27.500000,3.500000,NaN,0.0,0.194118,NaN,0.144737,0.040385,NaN,NaN
41,8708,12.500000,NaN,25.000000,5.000000,NaN,0.0,0.220588,NaN,0.131579,0.057692,NaN,NaN
42,8724,16.600000,NaN,61.800000,15.400000,NaN,0.0,0.292941,NaN,0.325263,0.177692,NaN,NaN
43,9990,NaN,NaN,132.000000,0.000000,NaN,0.0,NaN,NaN,0.694737,0.000000,NaN,NaN
44,10063,NaN,NaN,0.000000,5.000000,NaN,0.0,NaN,NaN,0.000000,0.057692,NaN,NaN
45,10262,12.666667,NaN,47.000000,6.000000,NaN,0.0,0.223529,NaN,0.247368,0.069231,NaN,NaN
46,10910,NaN,NaN,0.000000,15.000000,NaN,0.0,NaN,NaN,0.000000,0.173077,NaN,NaN
47,11175,10.500000,NaN,0.000000,0.000000,NaN,0.0,0.185294,NaN,0.000000,0.000000,NaN,NaN

In [95]:
competition_norm.to_csv(f"data_hub/{competition_name}_team_norm_data.csv", index = False)